### PR TITLE
Fix deprecation notices

### PR DESCRIPTION
**Pull request by mkardakov**
Fix deprecation notices related to Symfony 4.3+

https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching
https://github.com/symfony/symfony/issues/31877

### CODE REVIEW

**Comment by mkardakov** [comment]
@theodormanolescu , hey. I fixed tests and add some minor BC fixes. But I got this https://travis-ci.org/php-amqplib/RabbitMqBundle/jobs/572669764#L176. Is there any solution for that?

**Comment by christophe-mailfert** [comment]
Any news ?

**Comment by DemigodCode** [comment]
https://lorenzo.mile.si/travis-ci-and-composer-out-of-memory/739/

**Comment by mythxxx** [comment]
+1, this is really needed for PHP 4.3

**Comment by mihaileu** [comment]
For using the latest version, which have sy5/4.3 compatibility, please switch to the tag ^2.5.1.

**Pull request closed without merging**
