### PR TITLE
Fix Deprecations SF4.1

### PR DESCRIPTION
**Pull request by hjanuschka**
Fix deprecations

### CODE REVIEW

**Comment by DemigodCode** [comment]
Is it possible to merge this PR and create a new Tag? Everytime I compile the container this annoying deprecation occurs and will be posted to the monitoring.

**Comment by jorge07** [comment]
Any updates on this? Help wanted?

**Comment by SerkanYildiz** [comment]
ping @nubeiro

**Comment by MrSpoocy** [comment]
ping @chernecov please merge it, no BC, 3 lines of code but remove the warning

**Comment by chernecov** [comment]
@MrSpoocy, I would love to help, but I am not the maintainer :)

**Comment by DemigodCode** [comment]
@skafandri are you able to help?

**Comment by BentCoder** [comment]
Good job +1; Any idea on when to release this?

**Pull request merged**
