### PR TITLE
Align interface with the implementation of the Message Producer

### LINKED ISSUE #423: ProducerInterface not aligned with the implementation
The [publish method of the Producer](https://github.com/php-amqplib/RabbitMqBundle/blob/master/RabbitMq/Producer.php#L43) class can take an header also. This is not defined in the [interface](https://github.com/php-amqplib/RabbitMqBundle/blob/master/RabbitMq/ProducerInterface.php#L14)

### PR DESCRIPTION
**Pull request by mbiagetti**
close #423

### CODE REVIEW

**Comment by sebidchi** [comment]
Any news?

**Comment by akondas** [comment]
@skafandri is something blocking this MR?

**Comment by mbiagetti** [comment]
can i do something in order to merge this?

**Comment by markitosgv** [comment]
Could you please fix this? How can I put custom headers to my messages?

**Comment by dawidrylko** [comment]
idk @mbiagetti, still waiting 😞

**Comment by markitosgv** [comment]
any update?

**Comment by cawolf** [comment]
Hi all, can you tell me, what is blocking this PR from being merged? Can we help dealing with these issues?

**Comment by mbiagetti** [comment]
Thanks @marmichalski for the approval!
Are you take care of merging it?

**Comment by marmichalski** [comment]
@mbiagetti unfortunately not. I am also waiting for this to be merged.

**Comment by mihaileu** [comment]
Thanks for you PR

**Comment by mbiagetti** [comment]
@mihaileu You're welcome!

**Comment by mihaileu** [comment]
@mbiagetti I'll do a rollback and a new tag as this is a breaking change an it would require a new major release.
Maybe in the next major release we will include this.

https://github.com/php-amqplib/RabbitMqBundle/pull/625

**Comment by mihaileu** [comment]
We will include this fix in the next major version 3

**Pull request merged**
