### PR TITLE
Adding tests for Symfony 4 BETA

### PR DESCRIPTION
**Pull request by weaverryan**
Unless I'm mistaken, I don't think the tests are *yet* testing against Symfony 4. This adds that. 

As I mentioned in FriendsOfSymfony/FOSUserBundle#2639, there may be a better way of doing this. I'm happy to hear if there is :).

Cheers!

### CODE REVIEW

**Comment by weaverryan** [comment]
Actually, it *definitely* wasn't tested, as the tests failed :). I've pushed the small fix needed for Symfony 4 with an explanation in the commit.

Cheers!

**Comment by weaverryan** [comment]
Ping! This bundle is broken on 4.0 - this contains a simple fix. Could we merge and tag?

**Comment by weaverryan** [comment]
Ping @stloyd! Sorry to be annoying :). But this should be an easy merge and tag (there have been no commits to master since the last tag). Let's do this! Symfony 4.0 is Thursday

**Comment by stloyd** [comment]
@weaverryan Sorry for late merge, but had quite busy week (in fact few weeks ;)). But now it's merged, thanks!

**Comment by weaverryan** [comment]
Thank you! It's ok, I realize that I'm expecting a lot of quick attention from people currently. It's unreasonable. So, thank you :)

**Comment by weaverryan** [comment]
@stloyd Whoops - I forgot one favor! We need a 1.14.1 tag please!

**Pull request merged**
