### PR TITLE
Added method getCallback() in BaseConsumer

### PR DESCRIPTION
**Pull request by alinilie**

### CODE REVIEW

**Comment by skafandri** [comment]
is there a use case to get the callback from the consumer?

**Comment by alinilie** [comment]
My bad, i didn't write about the use case from the first time. Having this method will give you access to the callback from event listener (you already have consumer from method [getConsumer](https://github.com/php-amqplib/RabbitMqBundle/blob/dc96d6ee6d7d10345c037decd4874bcd330dcac8/Event/AMQPEvent.php#L55)).

**Comment by skafandri** [comment]
Ok, so we get the callback which is a `callable`, what can we do with it? Except executing it, which is happening anyway.

**Comment by alinilie** [comment]
I will use the class name to create a metric in Graphite (i have a listener for AMQPEvent::BEFORE_PROCESSING_MESSAGE).

**Comment by skafandri** [comment]
Be aware that it may return any `callable`, so handle it in your code.

**Pull request merged**
