### PR TITLE
Graceful max execution options is now available for MC

### PR DESCRIPTION
**Pull request by chernecov**
Graceful max execution options is now available for multiple consumers.

### CODE REVIEW

**Comment by chernecov** [comment]
Failing tests are not connected with changes:
`
5.3 is not pre-installed; installing
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-5.3.tar.bz2
0.16s$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
0.00s
0.01s$ phpenv global 5.3
rbenv: version `5.3' not installed
The command "phpenv global 5.3" failed and exited with 1 during .
`

**Comment by oleg-andreyev** [comment]
Just remove 5.3 from .travis.yml ;)

**Comment by acasademont** [comment]
Ah, this is what I was looking for!

**Comment by przemyslawlis** [comment]
This is much needed!

**Comment by oleg-andreyev** [comment]
@stloyd can you please review this PR?

**Comment by stloyd** [comment]
@oleg-andreyev Please rebase with latest master to make tests passing

**Comment by chernecov** [comment]
@stloyd Please, review.

**Comment by stloyd** [comment]
Looks good, thanks @chernecov !

**Comment by chernecov** [comment]
@stloyd Thanks you.
Can I ask you to review https://github.com/php-amqplib/RabbitMqBundle/pull/418
I really want these changes to be merged, and may be you would prefer different approach, in this case I would be happy to re-implement it according to your suggestions.
Thanks in advance.

**Pull request merged**
