### PR TITLE
Make 'old_sound_rabbit_mq.parts_holder' public

### PR DESCRIPTION
**Pull request by caciobanu**
Service 'old_sound_rabbit_mq.parts_holder' is used in Command/SetupFabricCommand.php

### CODE REVIEW

**Comment by caciobanu** [comment]
If you guys can tag after this it would be great :+1: .

**Comment by lku** [comment]
Is there chance to merge and release this PR? Without this fix the setup-fabric command is unusable under Symfony 4

screenshot from 2018-01-11 14-04-20

**Comment by stloyd** [comment]
Looks good, thanks @caciobanu !

**Comment by steveWinter** [comment]
Thank you for merging this PR - is there an eta for a tag with it in so that we don't need to rely on master in production SF 4 environments?

**Pull request merged**
